name: Fix Missing Release Tag

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version tag to create (e.g., 1.3.0)'
        required: true
        default: '1.3.0'
      commit_sha:
        description: 'Commit SHA to tag'
        required: true
        default: '3ca0655d73b0c38d37ce35337af5e8f58bf94e4c'

jobs:
  create-missing-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Validate inputs
        run: |
          echo "Creating tag v${{ github.event.inputs.version }} for commit ${{ github.event.inputs.commit_sha }}"
          
          # Verify commit exists
          if ! git cat-file -e ${{ github.event.inputs.commit_sha }}; then
            echo "ERROR: Commit ${{ github.event.inputs.commit_sha }} does not exist"
            exit 1
          fi
          
          # Verify commit is on main branch
          if ! git merge-base --is-ancestor ${{ github.event.inputs.commit_sha }} origin/main; then
            echo "ERROR: Commit is not on main branch"
            exit 1
          fi
          
          # Check if tag already exists
          if git ls-remote --tags origin | grep -q "refs/tags/v${{ github.event.inputs.version }}"; then
            echo "WARNING: Tag v${{ github.event.inputs.version }} already exists on remote"
          fi
          
      - name: Create and push tag
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          # Create the tag
          git tag -a "v${{ github.event.inputs.version }}" ${{ github.event.inputs.commit_sha }} -m "Release v${{ github.event.inputs.version }}

          This tag was created to fix a missing release.
          The CI workflow successfully created the release commit but failed to push the tag.
          
          Manual tag creation via workflow dispatch.
          "
          
          # Push the tag
          git push origin "v${{ github.event.inputs.version }}"
          
      - name: Verify tag creation
        run: |
          echo "✅ Tag v${{ github.event.inputs.version }} created successfully"
          echo "🚀 Release workflow should be triggered automatically"
          echo "📋 Check releases at: https://github.com/${{ github.repository }}/releases"
          echo "📋 Check actions at: https://github.com/${{ github.repository }}/actions"